### ISSUE TITLE
Transaction rollback fail when db is restart

### ISSUE THREAD

**Issue by BenderV** [dgilland/sqlservice#24]
Hi,
I'm battling with an issue for weeks now. My guess is that I'm a newbie to sqlalchemy, so I'm certain I make a stupid mistake somewhere.

Whenever I manually restart my db, my session can't seems to reconnect to it. It just throw 'InvalidRequestError'.

```
Traceback (most recent call last):
  File "/usr/src/app/project/process.py", line 235, in save
    "xxx": xxx
  File "/usr/local/lib/python3.6/site-packages/sqlservice/query.py", line 137, in save
    identity=identity)
  File "/usr/local/lib/python3.6/site-packages/sqlservice/core.py", line 195, in save
    _add(session, updatable, is_new=False, before=before, after=after)
  File "/usr/local/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/sqlservice/core.py", line 64, in transaction
    session.commit()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2171, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2291, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 76, in __exit__
    compat.reraise(type_, value, traceback)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2291, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 518, in rollback
    util.reraise(*rollback_err)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 490, in rollback
    transaction._rollback_impl()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 532, in _rollback_impl
    self.session.dispatch.after_rollback(self.session)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/event/attr.py", line 218, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy_continuum/manager.py", line 377, in clear
    if conn.connection is connection.connection:
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 351, in connection
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 349, in connection
    return self._revalidate_connection()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 424, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.InvalidRequestError: Can't reconnect until invalid transaction is rolled back
```

What should I do to fix it ? I have been thinking of wrapping with a try/except, closing the connection but I don't see where I can restart it.

**Comment by dgilland** [comment]
What version of sqlservice are you using (the line numbers in the traceback seem to be for an older version)?

It seems like what might have happen is that you lost the connection while this session was checked out and then tried to use the session and got the invalid request error. I'm curious if the try/except in `sqlservice.core:transaction` ended up calling `rollback()` which then re-raised the exception. You'd likely be able to use the connection after the error but obviously handling prior to this would be better.

Was this a part of a long running process by chance? If so, you might be keeping the connection/session open and not properly closing it. If you can provide some more details/context of what's happening in this process, I might be able to point you in the right direction with more recommendations (e.g. if using MySQL/MariaDB need to ensure pool timeout in client are less than wait timeout in database config).

Another option is to use the `SQL_POOL_PRE_PING` config option to `SQLClient` (sqlservice >= 0.15.0) to tell SQLAlchemy to ping the connection when checking it out (http://docs.sqlalchemy.org/en/latest/core/pooling.html#disconnect-handling-pessimistic). This does add some overhead when checking out a connection but it's more robust in that SQLAlchemy will invalidate the connection for you and attempt to reconnect when the ping fails. Things can still go wrong after the connection is checked out but rolling back and reconnecting should fix it. Usually SQLAlchemy will handle all this for you when you try to start the next db session (i.e. after you rollback, if the connection was invalidated, then SQLAlchemy will reconnect under the hood). So you just need to handle the failed transaction. But if the database is still down after the failed transaction, then you might want to try to detect that and handle that state appropriately.

**Comment by dgilland** [comment]
Closing due to inactivity. Feel free to reopened for further discussion.
